import { LegendBestand } from '../legends/LegendBestand'
import type { MapDataAndLegend } from './mapDataAndLegend.const'

export const pageBestand: MapDataAndLegend = {
  // todo: check if this matching is correct
  // "Bestand" in table = "Radinfrastruktur" in map / former website ?
  bestand: {
    sources: {
      roads: {
        pmTilesUrl: 'https://radverkehrsatlas.de/api/uploads/website-nudafa-roads',
        layers: [
          {
            filter: [
              'match',
              ['get', 'road'],
              [
                'residential',
                'living_street',
                'bicycle_road',
                'pedestrian',
                'unclassified',
                'residential_priority_road',
                'unspecified_road',
                'service_road',
                'service_alley',
              ],
              true,
              false,
            ],
            type: 'line',
            id: 'roadclassification-nomainstreet',
            paint: {
              'line-width': [
                'interpolate',
                ['linear'],
                ['zoom'],
                10,
                [
                  'case',
                  [
                    'match',
                    ['get', 'road'],
                    ['residential_priority_road', 'unclassified', 'living_street'],
                    true,
                    false,
                  ],
                  2.5,
                  [
                    'match',
                    ['get', 'road'],
                    [
                      'residential',
                      'living_street',
                      'cycleway',
                      'footway_sidewalk',
                      'pedestrian',
                      'bicycle_road',
                      'service_uncategorized',
                      'unspecified_road',
                      'service_alley',
                    ],
                    true,
                    false,
                  ],
                  1.5,
                  0.8,
                ],
                13,
                [
                  'case',
                  [
                    'match',
                    ['get', 'road'],
                    ['residential_priority_road', 'unclassified', 'living_street'],
                    true,
                    false,
                  ],
                  2,
                  [
                    'match',
                    ['get', 'road'],
                    [
                      'residential',
                      'living_street',
                      'cycleway',
                      'footway_sidewalk',
                      'pedestrian',
                      'bicycle_road',
                      'service_uncategorized',
                      'unspecified_road',
                      'service_alley',
                    ],
                    true,
                    false,
                  ],
                  1,
                  0.8,
                ],
                16,
                [
                  'case',
                  [
                    'match',
                    ['get', 'road'],
                    ['residential_priority_road', 'unclassified', 'living_street'],
                    true,
                    false,
                  ],
                  4,
                  [
                    'match',
                    ['get', 'road'],
                    [
                      'residential',
                      'living_street',
                      'cycleway',
                      'footway_sidewalk',
                      'pedestrian',
                      'bicycle_road',
                      'service_uncategorized',
                      'unspecified_road',
                      'service_alley',
                    ],
                    true,
                    false,
                  ],
                  2,
                  0.8,
                ],
              ],
              'line-color': [
                'match',
                ['get', 'road'],
                ['residential'],
                '#a2c9f6',
                ['living_street', 'bicycle_road', 'pedestrian'],
                '#447be9',
                ['unclassified', 'residential_priority_road', 'unspecified_road'],
                '#ffdb70',
                ['service_alley', 'service_road'],
                '#96e4b4',
                'rgba(213, 26, 26, 0.75)',
              ],
            },
          },
          {
            minzoom: 13,
            layout: {
              'line-cap': 'square',
              'line-miter-limit': 0,
            },
            filter: [
              'all',
              ['has', 'road_oneway'],
              ['match', ['get', 'road_oneway:bicycle'], ['no'], true, false],
              [
                'match',
                ['get', 'road'],
                [
                  'residential',
                  'living_street',
                  'bicycle_road',
                  'pedestrian',
                  'unclassified',
                  'residential_priority_road',
                  'unspecified_road',
                  'service_road',
                  'service_alley',
                ],
                true,
                false,
              ],
            ],
            type: 'line',
            id: 'roads-onewaybikeyes-pattern sidestreets',
            paint: {
              'line-pattern': 'arrow-blue-dots-gap(1)',
              'line-width': ['interpolate', ['linear'], ['zoom'], 13, 3, 15, 5, 22, 10],
              'line-opacity': 0.8,
            },
          },
          {
            minzoom: 13,
            layout: {
              'line-cap': 'square',
            },
            filter: [
              'all',
              ['match', ['get', 'road_oneway'], ['yes', 'implicit_yes'], true, false],
              [
                'match',
                ['get', 'road'],
                [
                  'residential',
                  'living_street',
                  'bicycle_road',
                  'pedestrian',
                  'unclassified',
                  'residential_priority_road',
                  'unspecified_road',
                  'service_road',
                  'service_alley',
                ],
                true,
                false,
              ],
            ],
            type: 'line',
            id: 'roads-oneway-pattern sidestreets',
            paint: {
              'line-pattern': 'arrow-grey-gap(1)',
              'line-width': ['interpolate', ['linear'], ['zoom'], 13, 3, 15, 5, 22, 10],
              'line-opacity': 0.7,
            },
          },
        ],
      },
      bikelanes: {
        pmTilesUrl: 'https://radverkehrsatlas.de/api/uploads/website-nudafa-bikelanes',
        layers: [
          {
            id: 'needsClarification',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-color': '#a97bea',
              'line-dasharray': [2.5, 0.5],
            },
            filter: ['match', ['get', 'category'], ['needsClarification'], true, false],
          },
          {
            id: 'Gehweg Rad frei',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-dasharray': [2, 2],
              'line-color': '#9fb9f9',
              'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
            },
            filter: [
              'match',
              ['get', 'category'],
              [
                'footwayBicycleYes_isolated',
                'pedestrianAreaBicycleYes',
                'footwayBicycleYes_adjoining',
                'footwayBicycleYes_adjoiningOrIsolated',
              ],
              true,
              false,
            ],
          },
          {
            id: 'Fuehrung mit Kfz-explizit',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-dasharray': [3, 1],
              'line-color': '#0098f0',
              'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
            },
            filter: [
              'match',
              ['get', 'category'],
              [
                'sharedMotorVehicleLane',
                'bicycleRoad_vehicleDestination',
                'sharedBusLaneBusWithBike',
                'explicitSharedLaneButNoSignage',
                'livingStreet',
              ],
              true,
              false,
            ],
          },
          {
            id: 'Fuehrung mit Fussverkehr',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-dasharray': [3, 1],
              'line-color': '#174ed9',
              'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
            },
            filter: [
              'match',
              ['get', 'category'],
              [
                'footAndCyclewayShared_isolated',
                'footAndCyclewayShared_adjoining',
                'footAndCyclewayShared_adjoiningOrIsolated',
              ],
              true,
              false,
            ],
          },
          {
            id: 'Fuehrung eigenstaendig auf Fahrbahn',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-color': '#0098f0',
              'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
            },
            filter: [
              'match',
              ['get', 'category'],
              [
                'cyclewayOnHighway_exclusive',
                'cyclewayOnHighwayBetweenLanes',
                'cyclewayLink',
                'crossing',
                'cyclewayOnHighway_advisory',
                'cyclewayOnHighway_advisoryOrExclusive',
              ],
              true,
              false,
            ],
          },
          {
            id: 'fuehrung baul. abgesetzt von Kfz',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 10, 1.5, 14, 2, 16, 3],
              'line-color': '#174ed9',
              'line-offset': ['interpolate', ['linear'], ['zoom'], 12, 0, 15, -1],
            },
            filter: [
              'match',
              ['get', 'category'],
              [
                'footAndCyclewaySegregated_adjoining',
                'footAndCyclewaySegregated_adjoiningOrIsolated',
                'cycleway_isolated',
                'cycleway_adjoining',
                'bicycleRoad',
                'footAndCyclewaySegregated_isolated',
                'cycleway_adjoiningOrIsolated',
              ],
              true,
              false,
            ],
          },
        ],
      },
    },
    legends: <LegendBestand />,
    colorClass: 'border-l-[#F5E4B7]',
  },
}
