import { LegendStrassentypen } from '../legends/LegendStrassentypen'
import type { MapDataAndLegend } from './mapDataAndLegend.const'

export const pageStrassentypen: MapDataAndLegend = {
  strassentypen: {
    sources: {
      'roads-legacy': {
        pmTilesUrl: 'https://radverkehrsatlas.de/api/uploads/website-nudafa-roads-legacy',
        layers: [
          {
            id: 'strassentyp',
            type: 'line',
            paint: {
              'line-color': [
                'case',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typWohnstrasse'],
                  ['true'],
                  true,
                  false,
                ],
                'hsl(163, 56%, 51%)',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typHauptUndSammelstrasse'],
                  ['true'],
                  true,
                  false,
                ],
                'hsl(50, 90%, 47%)',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typFreiGefuehrt'],
                  ['true'],
                  true,
                  false,
                ],
                'rgba(179, 107, 25, 0.67)',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typAusserorts'],
                  ['true'],
                  true,
                  false,
                ],
                'hsl(18, 97%, 47%)',
                ['==', ['get', 'FMC:Category:HighwayTypeData:typAusserorts'], ''],
                'hsla(97, 56%, 51%, 0)',
                'hsla(97, 56%, 51%, 0)',
              ],
              'line-opacity': 0.84,
              'line-width': [
                'interpolate',
                ['linear'],
                ['zoom'],
                0,
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typFreiGefuehrt'],
                  ['true'],
                  0.4,
                  0.5,
                ],
                11.5,
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typFreiGefuehrt'],
                  ['true'],
                  0.8,
                  1.5,
                ],
                22,
                ['match', ['get', 'FMC:Category:HighwayTypeData:typFreiGefuehrt'], ['true'], 2, 4],
              ],
            },
            filter: ['match', ['get', 'FMC:Category:HighwayTypeData'], ['true'], true, false],
          },
          {
            id: 'strassentyp-wohnstrassenonly',
            type: 'line',
            paint: {
              'line-width': ['interpolate', ['linear'], ['zoom'], 0, 0.5, 11.36, 0.5, 22, 5],
              'line-color': [
                'case',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typWohnstrasse'],
                  ['true'],
                  true,
                  false,
                ],
                '#c205a2',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typHauptUndSammelstrasse'],
                  ['true'],
                  true,
                  false,
                ],
                'hsl(50, 90%, 47%)',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typFreiGefuehrt'],
                  ['true'],
                  true,
                  false,
                ],
                'hsla(313, 18%, 69%, 0.37)',
                [
                  'match',
                  ['get', 'FMC:Category:HighwayTypeData:typAusserorts'],
                  ['true'],
                  true,
                  false,
                ],
                'hsl(18, 97%, 47%)',
                ['==', ['get', 'FMC:Category:HighwayTypeData:typAusserorts'], ''],
                'hsla(97, 56%, 51%, 0)',
                'hsla(97, 56%, 51%, 0)',
              ],
              'line-opacity': 0.38,
            },
            filter: [
              'all',
              ['match', ['get', 'FMC:Category:HighwayTypeData'], ['true'], true, false],
              [
                'match',
                ['get', 'FMC:Category:HighwayTypeData:typWohnstrasse'],
                ['true'],
                true,
                false,
              ],
              [
                'match',
                ['get', 'FMC:Category:SurfaceData:ScopeMainWay'],
                ['very_bad', 'bad'],
                false,
                true,
              ],
            ],
          },
        ],
      },
      // roads: {
      //   pmTilesUrl: 'https://radverkehrsatlas.de/api/uploads/website-nudafa-roads',
      //   layers: [
      //     {
      //       minzoom: 11,
      //       filter: [
      //         'all',
      //         ['has', 'road_oneway'],
      //         ['match', ['get', 'road_oneway:bicycle'], ['no', 'yes'], false, true],
      //         [
      //           'match',
      //           ['get', 'road'],
      //           [
      //             'motorway',
      //             'motorway_link',
      //             'primary',
      //             'primary_link',
      //             'trunk_link',
      //             'trunk',
      //             'secondary_link',
      //             'secondary',
      //           ],
      //           false,
      //           true,
      //         ],
      //       ],
      //       type: 'line',
      //       id: 'oneway-road',
      //       paint: {
      //         'line-color': [
      //           'match',
      //           ['get', 'road_oneway'],
      //           ['yes_dual_carriageway'],
      //           '#f1e9f2',
      //           ['yes'],
      //           '#fad329',
      //           '#000000',
      //         ],
      //         'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1, 22, 16],
      //       },
      //     },
      //     {
      //       minzoom: 11,
      //       filter: ['has', 'road_oneway:bicycle'],
      //       type: 'line',
      //       id: 'oneway-road-bicycle',
      //       paint: {
      //         'line-color': [
      //           'match',
      //           ['get', 'road_oneway:bicycle'],
      //           ['no'],
      //           '#54f8b6',
      //           ['yes'],
      //           '#fad329',
      //           'rgba(0, 0, 0, 0.22)',
      //         ],
      //         'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1, 22, 16],
      //       },
      //     },
      //     {
      //       minzoom: 13,
      //       layout: {
      //         'line-cap': 'square',
      //         'line-miter-limit': 0,
      //       },
      //       filter: [
      //         'all',
      //         ['match', ['get', 'road_oneway:bicycle'], ['no'], true, false],
      //         [
      //           'match',
      //           ['get', 'road'],
      //           [
      //             'motorway',
      //             'motorway_link',
      //             'primary',
      //             'primary_link',
      //             'trunk_link',
      //             'trunk',
      //             'secondary_link',
      //             'secondary',
      //           ],
      //           false,
      //           true,
      //         ],
      //       ],
      //       type: 'line',
      //       id: 'roads-onewaybikeyes-pattern plus',
      //       paint: {
      //         'line-pattern': 'arrow-blue-dots-gap(1)',
      //         'line-width': ['interpolate', ['linear'], ['zoom'], 13, 3, 15, 5, 22, 10],
      //         'line-opacity': 0.8,
      //       },
      //     },
      //     {
      //       minzoom: 13,
      //       layout: {
      //         'line-cap': 'square',
      //       },
      //       filter: [
      //         'all',
      //         ['has', 'road_oneway'],
      //         ['match', ['get', 'road_oneway'], ['yes', 'implicit_yes'], true, false],
      //         [
      //           'match',
      //           ['get', 'road'],
      //           [
      //             'motorway',
      //             'motorway_link',
      //             'primary',
      //             'primary_link',
      //             'trunk_link',
      //             'trunk',
      //             'secondary_link',
      //             'secondary',
      //           ],
      //           false,
      //           true,
      //         ],
      //       ],
      //       type: 'line',
      //       id: 'roads-oneway-pattern plus',
      //       paint: {
      //         'line-pattern': 'arrow-grey-gap(1)',
      //         'line-width': ['interpolate', ['linear'], ['zoom'], 13, 3, 15, 5, 22, 10],
      //         'line-opacity': 0.7,
      //       },
      //     },
      //   ],
      // },
    },
    legends: <LegendStrassentypen />,
  },
}
