// This file is only ever updated with the result from /radnetz/admin.
type LayerKey = string
type BelowLayerKey = string
export const beforeIds: Record<LayerKey, BelowLayerKey> = {
  'sicherheit-gefahrenstellen-nudafa-gefahrstellen': 'nudafa-beforeId-maskierung',
  'bestand-roads-Oberflaeche schlecht': 'sicherheit-unfaelle-nudafa-unfaelle',
  'sicherheit-unfaelle-nudafa-unfaelle': 'quellen-und-ziele-poi-POIs-Schulen',
  'quellen-und-ziele-poi-POIs-Schulen': 'Satellite',
  'Satellite': 'nudafa-beforeId-pagelayer',
  'nudafa-boundaries-gemeinden': 'kontext-vorhandene-netze-Vorhandene-netze_uebergeordnet',
  'kontext-vorhandene-netze-Vorhandene-netze_uebergeordnet': 'luftliniennetz-netzentwurf-nudafa-zielpunkte',
  'luftliniennetz-netzentwurf-nudafa-zielpunkte': 'strassentypen-roads-legacy-oneway-road-bicycle',
  'strassentypen-roads-legacy-oneway-road-bicycle': 'strassentypen-roads-legacy-roads-oneway-pattern plus',
  'strassentypen-roads-legacy-roads-oneway-pattern plus': 'bedarfe-combined-bedarfpunkt',
  'bedarfe-combined-bedarfpunkt': 'bedarfe-combined-Impulse fuer die Netzplanung',
  'bedarfe-combined-Impulse fuer die Netzplanung': 'bestand-roads-Oberflaeche gut oder sehr gut',
  'bestand-roads-Oberflaeche gut oder sehr gut': 'zielnetz-netzentwurf-nudafa-netzentwurf',
  'zielnetz-netzentwurf-nudafa-netzentwurf': 'massnahmen-netzentwurf-nudafa-netzentwurf s_w',
  'massnahmen-netzentwurf-nudafa-netzentwurf s_w': 'bestand-roads-fahradgeeigneteNebenstrassen',
  'bestand-roads-fahradgeeigneteNebenstrassen': 'quellen-und-ziele-barrier-lines-railway-rail',
  'quellen-und-ziele-barrier-lines-railway-rail': 'nudafa-maskierung-boundary',
  'nudafa-maskierung-boundary': 'einleitung-places-circle-place-names',
  'einleitung-places-circle-place-names': 'quellen-und-ziele-barrier-lines-railway_light_rail',
  'quellen-und-ziele-barrier-lines-railway_light_rail': 'quellen-und-ziele-landuse-landuse_residential-commercial -outlines',
  'quellen-und-ziele-landuse-landuse_residential-commercial -outlines': 'quellen-und-ziele-buildings-buildings-black',
  'quellen-und-ziele-buildings-buildings-black': 'luftliniennetz-netzentwurf-nudafa-luftlininien',
  'luftliniennetz-netzentwurf-nudafa-luftlininien': 'quellen-und-ziele-places-circle-place-circle',
  'quellen-und-ziele-places-circle-place-circle': 'quellen-und-ziele-barrier-lines-poibarriers_motorway',
  'quellen-und-ziele-barrier-lines-poibarriers_motorway': 'zielnetz-netzvorschlaege-buergerinnen-nudafa-netzvorschlaege-buergerinnen',
  'zielnetz-netzvorschlaege-buergerinnen-nudafa-netzvorschlaege-buergerinnen': 'quellen-und-ziele-places-circle-place-names',
  'quellen-und-ziele-places-circle-place-names': 'strassentypen-roads-legacy-strassentyp',
  'strassentypen-roads-legacy-strassentyp': 'dimmlayer-ZES-Betrachtungsraum',
  'dimmlayer-ZES-Betrachtungsraum': 'strassentypen-roads-legacy-roads-onewaybikeyes-pattern plus',
  'strassentypen-roads-legacy-roads-onewaybikeyes-pattern plus': 'strassentypen-roads-legacy-oneway-road',
  'strassentypen-roads-legacy-oneway-road': 'bedarfe-combined-Wichtige Ziele',
  'bedarfe-combined-Wichtige Ziele': 'komfort-roads-smoothness-roads-all',
  'komfort-roads-smoothness-roads-all': 'bestand-bikelanes-nudafa-bikelanes-fuehrungmitfuss',
  'bestand-bikelanes-nudafa-bikelanes-fuehrungmitfuss': 'nudafa-TransportationSprites',
  'quellen-und-ziele-barrier-lines-railway_light_rail-white': 'bedarfe-combined-bedarfstrecke',
  'bedarfe-combined-bedarfstrecke': 'einleitung-places-circle-place-circle',
  'einleitung-places-circle-place-circle': 'sicherheit-poi-POIs-Schulen',
  'sicherheit-poi-POIs-Schulen': 'Border-ZES-Betrachtungsraum',
  'Border-ZES-Betrachtungsraum': 'quellen-und-ziele-public-transport-publicTransport',
  'quellen-und-ziele-public-transport-publicTransport': 'quellen-und-ziele-barrier-areas-poibarriers_water_aerodrome',
  'quellen-und-ziele-barrier-areas-poibarriers_water_aerodrome': 'quellen-und-ziele-poi-poiShopCategory',
  'quellen-und-ziele-poi-poiShopCategory': 'quellen-und-ziele-poi-poiShopping-heatmap',
  'quellen-und-ziele-poi-poiShopping-heatmap': 'sicherheit-schulwege-nudafa-schulwege',
  'sicherheit-schulwege-nudafa-schulwege': 'nudafa-sprites-pattern',
  'bestand-bikelanes-nudafa-bikelanes-seperateinfra': 'housenumber',
  'quellen-und-ziele-landuse-landuse_residential-commercial': 'roadname_major',
  'quellen-und-ziele-barrier-lines-railway_rail-white': 'roadname_sec',
  'massnahmen-massnahmen-massnahmen alle': 'roadname_minor',
}
