// The file `src/components/page_radnetz/sortLayers/beforeIdEntries.const.ts` is only ever updated with the result from /radnetz/admin.
type LayerKey = string
type BelowLayerKey = string | undefined
export const beforeIdEntries: Array<{key: LayerKey, beforeId?: BelowLayerKey}> = [
// BOTTOM LAYERS OF THE MAP
{"key":"base-maskierung-dimmlayer-ZES-Betrachtungsraum"},
{"key":"base-maskierung-Border-ZES-Betrachtungsraum"},
{"key":"base-maskierung-boundary-nudafa-maskierung-boundary"},
{"key":"einleitung-places-circle-place-names","beforeId":"roadname_minor"},
{"key":"einleitung-places-circle-place-circle","beforeId":"roadname_minor"},
{"key":"kontext-vorhandene-netze-Vorhandene-netze_uebergeordnet","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-areas-poibarriers_water_aerodrome","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-buildings-buildings-black","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-lines-railway-rail","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-lines-railway_rail-white","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-lines-railway_light_rail","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-lines-railway_light_rail-white","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-barrier-lines-poibarriers_motorway","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-places-circle-place-circle","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-places-circle-place-names","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-poi-poiShopping-heatmap","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-poi-poiShopCategory","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-poi-POIs-Schulen","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-public-transport-publicTransport","beforeId":"watername_ocean"},
{"key":"komfort-roads-smoothness-roads-all","beforeId":"watername_ocean"},
{"key":"strassentypen-roads-oneway-roads-oneway","beforeId":"watername_ocean"},
{"key":"strassentypen-roads-legacy-strassentyp","beforeId":"watername_ocean"},
{"key":"bestand-roads-Oberflaeche schlecht","beforeId":"watername_ocean"},
{"key":"bestand-roads-Oberflaeche gut oder sehr gut","beforeId":"watername_ocean"},
{"key":"bestand-bikelanes-nudafa-bikelanes-seperateinfra","beforeId":"watername_ocean"},
{"key":"bestand-bikelanes-nudafa-bikelanes-fuehrungmitfuss","beforeId":"watername_ocean"},
{"key":"sicherheit-schulwege-nudafa-schulwege","beforeId":"watername_ocean"},
{"key":"sicherheit-unfaelle-nudafa-unfaelle","beforeId":"watername_ocean"},
{"key":"sicherheit-gefahrenstellen-nudafa-gefahrstellen","beforeId":"watername_ocean"},
{"key":"sicherheit-poi-POIs-Schulen","beforeId":"watername_ocean"},
{"key":"bedarfe-combined-bedarfstrecke","beforeId":"watername_ocean"},
{"key":"bedarfe-combined-bedarfpunkt","beforeId":"watername_ocean"},
{"key":"bedarfe-combined-Impulse fuer die Netzplanung","beforeId":"watername_ocean"},
{"key":"bedarfe-combined-Wichtige Ziele","beforeId":"watername_ocean"},
{"key":"luftliniennetz-netzentwurf-nudafa-luftlininien","beforeId":"watername_ocean"},
{"key":"luftliniennetz-netzentwurf-nudafa-zielpunkte","beforeId":"watername_ocean"},
{"key":"zielnetz-roads-Oberflaeche gut oder sehr gut","beforeId":"watername_ocean"},
{"key":"zielnetz-netzvorschlaege-buergerinnen-nudafa-netzvorschlaege-buergerinnen","beforeId":"watername_ocean"},
{"key":"zielnetz-netzentwurf-nudafa-netzentwurf","beforeId":"watername_ocean"},
{"key":"massnahmen-netzentwurf-nudafa-netzentwurf","beforeId":"watername_ocean"},
{"key":"massnahmen-massnahmen-massnahmen linien","beforeId":"watername_ocean"},
{"key":"massnahmen-massnahmen-massnahmen punkte","beforeId":"watername_ocean"},
{"key":"base-boundaries-nudafa-boundaries-gemeinden","beforeId":"watername_ocean"},
{"key":"quellen-und-ziele-landuse-landuse_residential-commercial -outlines","beforeId":"Satellite"},
{"key":"quellen-und-ziele-landuse-landuse_residential-commercial","beforeId":"Satellite"}
// TOP LAYERS OF THE MAP
]
