export const beforeIds: Record<string, Record<string, string>> = {
  einleitung: {
    'einleitung-places-circle-place-circle': 'poi_park',
    'einleitung-places-circle-place-names': 'einleitung-places-circle-place-circle',
  },
  kontext: {
    'kontext-vorhandene-netze-Vorhandene-netze_uebergeordnet': 'roadname_major',
  },
  todo: {
    'buildings-buildings-black': 'housenumber',
    'landuse-landuse_residential-commercial -outlines': 'buildings-buildings-black',
    'landuse-landuse_residential-commercial': 'landuse-landuse_residential-commercial -outlines',
    'barrier-areas-poibarriers_water_aerodrome': 'landuse-landuse_residential-commercial',
    'barrier-lines-railway-rail': 'barrier-areas-poibarriers_water_aerodrome',
    'barrier-lines-railway_rail-white': 'barrier-lines-railway-rail',
    'barrier-lines-railway_light_rail': 'barrier-lines-railway_rail-white',
    'barrier-lines-railway_light_rail-white': 'barrier-lines-railway_light_rail',
    'barrier-lines-poibarriers_motorway': 'barrier-lines-railway_light_rail-white',
    'roads-roadclassification-nomainstreet': 'barrier-lines-poibarriers_motorway',
    'roads-roads-onewaybikeyes-pattern sidestreets': 'roads-roadclassification-nomainstreet',
    'roads-roads-oneway-pattern sidestreets': 'roads-roads-onewaybikeyes-pattern sidestreets',
    'bikelanes-needsClarification': 'roadname_major',
    'bikelanes-Gehweg Rad frei': 'bikelanes-needsClarification',
    'bikelanes-Fuehrung mit Kfz-explizit': 'bikelanes-Gehweg Rad frei',
    'bikelanes-Fuehrung mit Fussverkehr': 'bikelanes-Fuehrung mit Kfz-explizit',
    'bikelanes-Fuehrung eigenstaendig auf Fahrbahn': 'bikelanes-Fuehrung mit Fussverkehr',
    'bikelanes-fuehrung baul. abgesetzt von Kfz': 'bikelanes-Fuehrung eigenstaendig auf Fahrbahn',
    'roads-smoothness-roads-all': 'bikelanes-fuehrung baul. abgesetzt von Kfz',
    'vorhandene-netze-Vorhandene-netze_uebergeordnet': 'roads-smoothness-roads-all',
    'schulwege-nudafa-schulwege': 'vorhandene-netze-Vorhandene-netze_uebergeordnet',
    'unfaelle-nudafa-unfaelle': 'schulwege-nudafa-schulwege',
    'gefahrenstellen-nudafa-gefahrstellen': 'unfaelle-nudafa-unfaelle',
    'poi-pois-heat copy': 'gefahrenstellen-nudafa-gefahrstellen',
    'poi-education-classification-edu-names': 'poi-pois-heat copy',
    'poi-education-classification-edu': 'poi-education-classification-edu-names',
    'roads-legacy-strassentyp': 'poi-education-classification-edu',
    'roads-legacy-oneway-road': 'roads-legacy-strassentyp',
    'roads-legacy-oneway-road-bicycle': 'roads-legacy-oneway-road',
    'roads-legacy-roads-onewaybikeyes-pattern plus': 'roads-legacy-oneway-road-bicycle',
    'roads-legacy-roads-oneway-pattern plus': 'roads-legacy-roads-onewaybikeyes-pattern plus',
    'combined-Luftlinien': 'roads-legacy-roads-oneway-pattern plus',
    'ziel-zwangspunkte-Zielpunkte': 'combined-Luftlinien',
    'ziel-zwangspunkte-Zwangspunkte': 'ziel-zwangspunkte-Zielpunkte',
    'combined-Netzentwurf': 'ziel-zwangspunkte-Zwangspunkte',
    'netzvorschlaege-buergerinnen-nudafa-netzvorschlaege-buergerinnen': 'combined-Netzentwurf',
    // "ziel-zwangspunkte-Zwangspunkte":"netzvorschlaege-buergerinnen-nudafa-netzvorschlaege-buergerinnen",
    'combined-Problemstrecke': 'ziel-zwangspunkte-Zwangspunkte',
    'combined-Problempunkt': 'combined-Problemstrecke',
    'combined-Ergaenzungsvorschlag Route': 'combined-Problempunkt',
    'combined-wichtige Ziele aus Beteiligung': 'combined-Ergaenzungsvorschlag Route',
    'places-circle-place-circle': 'poi_park',
    'places-circle-place-names': 'places-circle-place-circle',
    'poi-poiShopping-heatmap': 'places-circle-place-names',
    'poi-poiShopCategory': 'poi-poiShopping-heatmap',
    'poi-poiEducation-schoolsafety': 'poi-poiShopCategory',
    'poi-poiEducation-label': 'poi-poiEducation-schoolsafety',
    'public-transport-publictransport': 'poi-poiEducation-label',
    // "places-circle-place-circle":"public-transport-publictransport",
    // "places-circle-place-names":"places-circle-place-circle",
  },
}
